version: '2'

services:
  app:
    image: kamchy/stoic-backend:latest
    build:
      context: .
    container_name: stoic-backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stoic_db
      - SPRING_DATASOURCE_USERNAME=stoic
      - SPRING_DATASOURCE_PASSWORD=stoic
      - SERVER_PORT=${SERVER_PORT}
      - GUI_PORT=${GUI_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  gui:
    container_name: stoic-frontend
    image: kamchy/stoic-frontend:latest
    build:
      context: ../simple
    depends_on:
      - app
    environment:
      REACT_APP_SERVER_PORT: ${SERVER_PORT}
      REACT_APP_GUI_PORT: ${GUI_PORT}
    ports:
      - "${GUI_PORT}:80"
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=stoic
      - POSTGRES_PASSWORD=stoic
      - POSTGRES_DB=stoic_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
